# Managed by terraform from railsware/mailtrap-github-terraform
# https://github.com/kentaro-m/auto-assign/

# Set to true to add reviewers to pull requests
addReviewers: true
# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
#reviewers:

reviewGroups:
  squad_1:
    - VladimirTaytor # Volodymyr Pihol
    - r4do # Kirill Mikhailets
    - Lorenc326 # Ihor Kruk
  squad_2:
    - IgorDobryn # Igor Dobryn
    - i7an # Ivan Yurchanka
    - ayanko # Andriy Yanko
  squad_3:
    - leonid-shevtsov # Leonid Shevtsov
    - yvasilkov # Yaroslav Vasilkov
    - mklocek # Marcin Klocek
    - charlesjom # Charles Jo Marquez

# A list of assignees, overrides reviewers if set
# assignees:
# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
# or a number of reviewers taken from each reviewer group
numberOfReviewers: 1
